[package]
name = "aws-ec2-manager-tauri"
version = "0.1.0"
description = "AWS EC2 Manager App"
authors = ["you"]
edition = "2021"

[lib]
name = "aws_ec2_manager_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
aws-config = { version = "1", features = ["behavior-version-latest", "rustls"] }
aws-credential-types = { version = "1", features = ["hardcoded-credentials"] }
aws-sdk-ec2 = "1"
aws-sdk-costexplorer = "1"
aws-sdk-ecs = "1"
aws-sdk-applicationautoscaling = "1"
chrono = "0.4"
aws-smithy-runtime = { version = "1", features = ["tls-rustls"] }
aws-smithy-runtime-api = "1"
hyper-rustls = { version = "0.24", features = ["http2", "webpki-roots"] }
